# src/settings.py
import pygame

# --- Główne Ustawienia Okna ---
INITIAL_SCREEN_WIDTH = 1436
INITIAL_SCREEN_HEIGHT = 1024
GAMEPLAY_SCREEN_WIDTH = 1436
GAMEPLAY_SCREEN_HEIGHT = 1024
SCREEN_TITLE = "Wyścig po Zaliczenie"
FPS = 60

# --- Kolory ---
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
DEFAULT_BG_COLOR = BLACK
MENU_BG_FALLBACK_COLOR = (200, 180, 160)
MENU_BUTTON_BASE_COLOR = (240, 190, 100)
MENU_BUTTON_HOVER_COLOR = (255, 210, 120)
MENU_TEXT_COLOR = (80, 50, 20)
MENU_TITLE_COLOR = MENU_TEXT_COLOR
PANEL_BG_COLOR = (50, 50, 70)
PANEL_TEXT_COLOR_INFO = (220, 220, 220)
PANEL_BUTTON_BASE_COLOR = MENU_BUTTON_BASE_COLOR
PANEL_BUTTON_HOVER_COLOR = MENU_BUTTON_HOVER_COLOR
PANEL_BUTTON_TEXT_COLOR = MENU_TEXT_COLOR
LEFT_PANEL_WIDTH = 412
BOARD_BG_FALLBACK_COLOR = (200, 180, 160)
FIELD_LABEL_TEXT_COLOR = (10, 10, 10)
FIELD_LABEL_BG_COLOR_SUBJECT = (230, 230, 210)
FIELD_LABEL_BG_COLOR_SPECIAL = (200, 220, 240)
FIELD_LABEL_BG_COLOR_START = (180, 240, 180)
DICE_FALLBACK_IMAGE_COLOR = (255, 0, 0)

# Kolory dla Karty Pytania
QUESTION_CARD_BG_COLOR = (245, 245, 220)
QUESTION_CARD_TEXT_COLOR = (80, 50, 20)
ANSWER_BUTTON_HOVER_COLOR = (242, 182, 53, 50)
ANSWER_CORRECT_COLOR = (144, 238, 144, 150)
ANSWER_INCORRECT_COLOR = (255, 105, 97, 150)

# --- Ścieżki do Zasobów ---
BASE_ASSET_PATH = "../assets/"
FONT_PATH_PT_SERIF_REGULAR = BASE_ASSET_PATH + "fonts/PTSerif-Regular.ttf"
FONT_PATH_NOTO_SERIF_REGULAR = BASE_ASSET_PATH + "fonts/NotoSerif_Condensed-Black.ttf"
FONT_PATH_HUNINN_REGULAR = BASE_ASSET_PATH + "fonts/Huninn-Regular.ttf"
IMAGE_PATH_MENU_BG = BASE_ASSET_PATH + "images/MENU_GLOWNE.png"
IMAGE_PATH_ICON = BASE_ASSET_PATH + "images/IKONA_GRY.png"
IMAGE_PATH_GAMEPLAY_LEFT_PANEL_BG = BASE_ASSET_PATH + "images/GAMEBOARD_LEFT_PANEL.png"
IMAGE_PATH_BOARD_BG = BASE_ASSET_PATH + "images/PLANSZA_GRY.png"
IMAGE_PATH_QUESTION_CARD_BG = BASE_ASSET_PATH + "images/KARTA_PYTANIA.png"
IMAGE_PATH_PLAYER1_PAWN = BASE_ASSET_PATH + "images/PIONEK_STUDENT1.png"
IMAGE_PATH_PLAYER2_PAWN = BASE_ASSET_PATH + "images/PIONEK_STUDENT2.png"
IMAGE_PATH_PROFESSOR_PAWN = BASE_ASSET_PATH + "images/PIONEK_PROFESOR.png"
IMAGE_PATH_PLAYER_WIDGET_BG = BASE_ASSET_PATH + "images/WIDGET_GRACZA1.png"
IMAGE_PATH_PLAYER_WIDGET_BG_2 = BASE_ASSET_PATH + "images/WIDGET_GRACZA2.png"
IMAGE_PATH_ECTS_ICON = BASE_ASSET_PATH + "images/ECTS_ICON.png"
IMAGE_PATH_HEART_ICON = BASE_ASSET_PATH + "images/HEART_ICON.png"
IMAGE_PATH_EMPTY_HEART_ICON = BASE_ASSET_PATH + "images/EMPTY_HEART_ICON.png"
IMAGE_PATH_INSTRUCTIONS_BG = BASE_ASSET_PATH + "images/INSTRUCTIONS_BG.png"
DICE_IMAGES_BASE_PATH = BASE_ASSET_PATH + "images/"

# --- Ustawienia Czcionek ---
MENU_TITLE_FONT_SIZE = 90
MENU_BUTTON_FONT_SIZE = 40
BOARD_LABEL_FONT_SIZE = 18
GAMEPLAY_PANEL_INFO_FONT_SIZE = 28
GAMEPLAY_PANEL_BUTTON_FONT_SIZE = 30
PLAYER_WIDGET_NAME_FONT_SIZE = 19
PLAYER_WIDGET_POINTS_FONT_SIZE = 30
NAME_INPUT_FONT_SIZE = 40
NAME_INPUT_LABEL_FONT_SIZE = 35
NAME_ERROR_FONT_SIZE = 24
QUESTION_CARD_QUESTION_FONT_SIZE = 32
QUESTION_CARD_ANSWER_FONT_SIZE = 28
QUESTION_CARD_ANSWER_LABEL_FONT_SIZE = 48

# --- Ustawienia Punktacji i Żyć ---
INITIAL_PLAYER_LIVES = 3
POINTS_FOR_CORRECT_ANSWER = 1
POINTS_FOR_SCHOLARSHIP = 2
POINTS_FOR_RETAKE = -2
POINTS_FOR_EXAM_CORRECT = 1
POINTS_FOR_EXAM_INCORRECT = -1

# --- Ustawienia Przycisków Menu ---
MENU_BUTTON_WIDTH = 470
MENU_BUTTON_HEIGHT = 115
MENU_BUTTON_SPACING = 20
MENU_BUTTON_START_Y_OFFSET_PERCENTAGE = 0.59
MENU_BUTTON_CENTER_X_OFFSET = -140

# --- Ustawienia Przycisków Panelu Gameplay ---
GAMEPLAY_PANEL_BUTTON_WIDTH = 220
GAMEPLAY_PANEL_BUTTON_HEIGHT = 70
GAMEPLAY_PANEL_BUTTON_SPACING = 20
MAX_PLAYER_NAME_LENGTH = 20

# --- Ustawienia Ekranu Wprowadzania Imion ---
NAME_INPUT_BOX_WIDTH = 450
NAME_INPUT_BOX_HEIGHT = 60
NAME_INPUT_LABEL_Y_OFFSET = -50
NAME_INPUT_LABEL_X_OFFSET = 0
NAME_ERROR_COLOR = (200, 0, 0)
NAME_ERROR_DURATION_SECONDS = 1.0
NAME_ERROR_Y_OFFSET = 10

# --- Ustawienia Karty Pytania ---
QUESTION_CARD_WIDTH = 614
QUESTION_CARD_HEIGHT = 921
QUESTION_CARD_BORDER_RADIUS = 25
QUESTION_TEXT_AREA_RECT = pygame.Rect(90, 330, 430, 190)
ANSWER_A_CLICK_RECT = pygame.Rect(89, 550, 436, 77)
ANSWER_B_CLICK_RECT = pygame.Rect(89, 649, 436, 77)
ANSWER_C_CLICK_RECT = pygame.Rect(89, 747, 436, 77)
ANSWER_D_CLICK_RECT = pygame.Rect(89, 845, 436, 77)
ANSWER_TEXT_AREA_PADDING_X = 50
ANSWER_TEXT_AREA_PADDING_Y = 5
ANSWER_LABEL_CENTER_X = 40
ANSWER_HOVER_BORDER_RADIUS = 10
FEEDBACK_DURATION_SECONDS = 2.0
INTER_QUESTION_DELAY_SECONDS = 0.4

# --- Ustawienia Kostki ---
DICE_IMAGE_WIDTH = 120
DICE_IMAGE_HEIGHT = 120
DICE_ANIMATION_DURATION_SECONDS = 0.5
DICE_ANIMATION_FRAME_DURATION_SECONDS = 0.05

# --- Ustawienia Planszy ---
BOARD_RENDER_WIDTH = 1024
BOARD_RENDER_HEIGHT = 1024

# --- Ustawienia Pionków ---
PAWN_TARGET_HEIGHT = 70
PAWN_FALLBACK_COLOR = (255, 0, 0)
PAWN_MOVE_SPEED_PIXELS_PER_SECOND = 300

# --- Ustawienia Widgetu Gracza ---
PLAYER_WIDGET_WIDTH = 405
PLAYER_WIDGET_HEIGHT = 157
PLAYER_WIDGET_1_X_OFFSET = ((LEFT_PANEL_WIDTH - PLAYER_WIDGET_WIDTH) // 2) + 15
PLAYER_WIDGET_1_Y_OFFSET = 30
PLAYER_WIDGET_VERTICAL_SPACING = 15
PLAYER_WIDGET_TEXT_X_PADDING = 140
PLAYER_WIDGET_TEXT_Y_OFFSET = -7
PLAYER_WIDGET_ECTS_ICON_SIZE = 50
PLAYER_WIDGET_ECTS_ICON_X = 140
PLAYER_WIDGET_ECTS_ICON_Y = 100
PLAYER_WIDGET_ECTS_TEXT_X_OFFSET = 3
PLAYER_WIDGET_FLOATING_TEXT_X_OFFSET = 30
PLAYER_WIDGET_FLOATING_TEXT_Y_OFFSET = -10
FLOATING_TEXT_SPEED_Y = -30
FLOATING_TEXT_DURATION_SECONDS = 1.0
PLAYER_WIDGET_HEART_ICON_SIZE = 35
PLAYER_WIDGET_HEARTS_START_X = 240
PLAYER_WIDGET_HEARTS_Y = 108
PLAYER_WIDGET_HEARTS_SPACING = 5
WIDGET_SHAKE_DURATION_SECONDS = 0.4
WIDGET_SHAKE_INTENSITY = 4
WIDGET_SHAKE_FREQUENCY = 0.05
WIDGET_PULSE_DURATION_SECONDS = 1.0
WIDGET_PULSE_SCALE_MAX = 1.4
WIDGET_PULSE_SPEED = 5.0

# --- Ustawienia Profesora ---
PROFESSOR_BASE_MOVE_TURN_INTERVAL = 3

# === NOWA, POPRAWNA SEKCJA DLA EKRANU INSTRUKCJI ===
# Zastępuje poprzednie, potencjalnie błędne wpisy

# Kolory dla pełnoekranowej instrukcji
INSTRUCTIONS_FALLBACK_BG_COLOR = (40, 30, 20)
INSTRUCTIONS_TITLE_COLOR = (240, 190, 100)
INSTRUCTIONS_HEADER_COLOR = (220, 220, 200)
INSTRUCTIONS_BODY_COLOR = (200, 200, 180)

# Czcionki dla instrukcji (dodane do głównej sekcji czcionek wyżej)
INSTRUCTIONS_TITLE_FONT_SIZE = 80
INSTRUCTIONS_HEADER_FONT_SIZE = 42
INSTRUCTIONS_BODY_FONT_SIZE = 28

# Pozycjonowanie na pełnym ekranie
INSTRUCTIONS_TITLE_Y = 80
INSTRUCTIONS_CONTENT_START_Y = 140
INSTRUCTIONS_CONTENT_X_PADDING = 100
INSTRUCTIONS_LINE_SPACING = 1.3
INSTRUCTIONS_SECTION_SPACING = 3
INSTRUCTIONS_BULLET_INDENT = 40

# Przycisk powrotu
INSTRUCTIONS_BACK_BUTTON_WIDTH = 300
INSTRUCTIONS_BACK_BUTTON_HEIGHT = 80
INSTRUCTIONS_BACK_BUTTON_Y_OFFSET = -60
# ===================================================