# src/settings.py

import pygame

# --- Główne Ustawienia Okna ---
INITIAL_SCREEN_WIDTH = 1436
INITIAL_SCREEN_HEIGHT = 1024
GAMEPLAY_SCREEN_WIDTH = 1436
GAMEPLAY_SCREEN_HEIGHT = 1024
SCREEN_TITLE = "Wyścig po Zaliczenie"
FPS = 60

# --- Kolory ---
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
DEFAULT_BG_COLOR = BLACK
MENU_BG_FALLBACK_COLOR = (200, 180, 160)
MENU_BUTTON_BASE_COLOR = (240, 190, 100)
MENU_BUTTON_HOVER_COLOR = (255, 210, 120)
MENU_TEXT_COLOR = (80, 50, 20)
MENU_TITLE_COLOR = MENU_TEXT_COLOR
PANEL_BG_COLOR = (50, 50, 70)
PANEL_TEXT_COLOR_INFO = (220, 220, 220)
PANEL_BUTTON_BASE_COLOR = MENU_BUTTON_BASE_COLOR
PANEL_BUTTON_HOVER_COLOR = MENU_BUTTON_HOVER_COLOR
PANEL_BUTTON_TEXT_COLOR = MENU_TEXT_COLOR
LEFT_PANEL_WIDTH = 412
BOARD_BG_FALLBACK_COLOR = (200, 180, 160)
FIELD_LABEL_TEXT_COLOR = (10, 10, 10)
FIELD_LABEL_BG_COLOR_SUBJECT = (230, 230, 210)
FIELD_LABEL_BG_COLOR_SPECIAL = (200, 220, 240)
FIELD_LABEL_BG_COLOR_START = (180, 240, 180)
DICE_FALLBACK_IMAGE_COLOR = (255, 0, 0)

# --- Ścieżki do Zasobów ---
BASE_ASSET_PATH = "../assets/"
FONT_PATH_PT_SERIF_REGULAR = BASE_ASSET_PATH + "fonts/PTSerif-Regular.ttf"

IMAGE_PATH_MENU_BG = BASE_ASSET_PATH + "images/MENU_GLOWNE.png"
IMAGE_PATH_ICON = BASE_ASSET_PATH + "images/IKONA_GRY.png"
IMAGE_PATH_GAMEPLAY_LEFT_PANEL_BG = BASE_ASSET_PATH + "images/GAMEBOARD_LEFT_PANEL.png"
IMAGE_PATH_BOARD_BG = BASE_ASSET_PATH + "images/PLANSZA_GRY.png"

IMAGE_PATH_PLAYER1_PAWN = BASE_ASSET_PATH + "images/PIONEK_STUDENT1.png"
IMAGE_PATH_PLAYER2_PAWN = BASE_ASSET_PATH + "images/PIONEK_STUDENT2.png"
IMAGE_PATH_PROFESSOR_PAWN = BASE_ASSET_PATH + "images/PIONEK_PROFESOR.png"

IMAGE_PATH_PLAYER_WIDGET_BG = BASE_ASSET_PATH + "images/WIDGET_GRACZA1.png"
IMAGE_PATH_PLAYER_WIDGET_BG_2 = BASE_ASSET_PATH + "images/WIDGET_GRACZA2.png" #

DICE_IMAGES_BASE_PATH = BASE_ASSET_PATH + "images/"

# --- Ustawienia Czcionek ---
MENU_TITLE_FONT_SIZE = 90
MENU_BUTTON_FONT_SIZE = 40
BOARD_LABEL_FONT_SIZE = 18
GAMEPLAY_PANEL_INFO_FONT_SIZE = 28
GAMEPLAY_PANEL_BUTTON_FONT_SIZE = 30
PLAYER_WIDGET_FONT_SIZE = 32
NAME_INPUT_FONT_SIZE = 40
NAME_INPUT_LABEL_FONT_SIZE = 35

# --- Ustawienia Przycisków Menu ---
MENU_BUTTON_WIDTH = 470
MENU_BUTTON_HEIGHT = 115
MENU_BUTTON_SPACING = 20
MENU_BUTTON_START_Y_OFFSET_PERCENTAGE = 0.59
MENU_BUTTON_CENTER_X_OFFSET = -140

# --- Ustawienia Przycisków Panelu Gameplay ---
GAMEPLAY_PANEL_BUTTON_WIDTH = 220
GAMEPLAY_PANEL_BUTTON_HEIGHT = 70
GAMEPLAY_PANEL_BUTTON_SPACING = 20

# --- Ustawienia Ekranu Wprowadzania Imion ---
NAME_INPUT_BOX_WIDTH = 450
NAME_INPUT_BOX_HEIGHT = 60
NAME_INPUT_LABEL_Y_OFFSET = -40

# --- Ustawienia Kostki ---
DICE_IMAGE_WIDTH = 120
DICE_IMAGE_HEIGHT = 120
DICE_ANIMATION_DURATION_SECONDS = 0.5
DICE_ANIMATION_FRAME_DURATION_SECONDS = 0.05

# --- Ustawienia Planszy ---
BOARD_RENDER_WIDTH = 1024
BOARD_RENDER_HEIGHT = 1024

# --- Ustawienia Pionków ---
PAWN_TARGET_HEIGHT = 70
PAWN_FALLBACK_COLOR = (255, 0, 0)
PAWN_MOVE_SPEED_PIXELS_PER_SECOND = 300

# --- Ustawienia Widgetu Gracza ---
PLAYER_WIDGET_WIDTH = 405   # Szerokość grafiki widgetu
PLAYER_WIDGET_HEIGHT = 157   # Wysokość grafiki widgetu

# --- Ustawienia Pozycjonowania Widgetów ---
PLAYER_WIDGET_1_X_OFFSET = ((LEFT_PANEL_WIDTH - PLAYER_WIDGET_WIDTH) // 2) + 15 # Centrowanie
PLAYER_WIDGET_1_Y_OFFSET = 30 # Odstęp od góry
PLAYER_WIDGET_VERTICAL_SPACING = 15 # Odstęp między widgetami

# --- Pozycjonowanie Tekstu w Widgecie ---
PLAYER_WIDGET_TEXT_X_PADDING = 140 # Odstęp od lewej krawędzi widgetu
PLAYER_WIDGET_TEXT_Y_OFFSET = -7 # Dodatkowe przesunięcie w pionie od środka

# --- Ustawienia Ekranu Wprowadzania Imion ---
NAME_INPUT_BOX_WIDTH = 450
NAME_INPUT_BOX_HEIGHT = 60
NAME_INPUT_LABEL_Y_OFFSET = -50
NAME_INPUT_LABEL_X_OFFSET = 0